spring.application.name=chat
server.port=8082

#langchain4j.open-ai.chat-model.api-key=${ALI_API_KEY}
#langchain4j.open-ai.chat-model.model-name=qwen-max
#langchain4j.open-ai.chat-model.log-requests=true
#langchain4j.open-ai.chat-model.log-responses=true

#langchain4j.open-ai.streaming-chat-model.api-key=${ALI_API_KEY}
#langchain4j.open-ai.streaming-chat-model.model-name=qwen-max
#langchain4j.open-ai.streaming-chat-model.log-requests=true
#langchain4j.open-ai.streaming-chat-model.log-responses=true


# 注入QwenChatModel对象需要配置api-key
langchain4j.community.dashscope.chat-model.api-key=${ALI_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=qwen-max

# 注入QwenStreamingChatModel需要配置api-key
langchain4j.community.dashscope.streaming-chat-model.api-key=${ALI_API_KEY}
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen-max

langchain4j.community.dashscope.embedding-model.api-key=${ALI_API_KEY}

logging.level.dev.langchain4j=DEBUG

management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1
#本地没有Zipkin服务,先把监控关了
management.tracing.enabled=false